# Production Configuration
spring:
  datasource:
    url: jdbc:mysql://mysql-0.mysql.pillguide.svc.cluster.local:3306/pillguide_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: 941227

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: info
    com.wedit: debug
    org.hibernate.sql: debug

springdoc:
  swagger-ui:
    enabled: true