jar {
    enabled = false
}

bootJar {
    enabled = true
}

dependencies {

    // Spring Validation
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // Spring Web
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // [DEV] Spring Devtools
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
}